# Dockerfile

# Build: docker build -t alpine-base:3.7 .
# Run: docker run -it alpine-base:3.7

FROM alpine:3.7
MAINTAINER Virantha Mendis

RUN apk --no-cache update && \
    apk --no-cache upgrade

# ENTRYPOINT ["sh"]
CMD ["sh"]
